cluster.name: "docker-cluster"
network.host: 0.0.0.0
# xpack.security.enabled: true
# xpack.security.http.ssl.enabled: true
# xpack.security.transport.ssl.enabled: true
xpack.security.enrollment.enabled: true
# xpack.security.http.ssl.key: /path/to/elasticsearch/config/node-key.pem
# xpack.security.http.ssl.certificate: /path/to/elasticsearch/config/node.pem
