# Generated by Django 5.0.1 on 2024-01-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='pseudo',
            field=models.CharField(default='default_pseudo', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='unique_id',
            field=models.BigAutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
