version: '3'

services:

  frontend:
    build:
      context: ./requirements/frontend/src
      dockerfile: Dockerfile
    volumes:
      - ./requirements/frontend/src:/usr/share/nginx/html
    ports:
      - "8001:80"
    restart: on-failure

  ludo:
    build:
      context: ./requirements/ludo
      dockerfile: Dockerfile
    volumes:
      - ./requirements/ludo/ludo_project:/app
    ports:
      - "8002:8000"
    networks:
      - atlas

    # User container
  Alfred:
    build:
      context: ./requirements/alfred
      dockerfile: Dockerfile
    volumes:
      ./requirements/alfred/alfred_project:/app
    ports:
      - "8003:8000"
    networks:
      - atlas

networks:
  atlas:
    driver: bridge
