version: '3'

services:

# Front container
  frontend:
    build:
      context: ./requirements/frontend/src
      dockerfile: Dockerfile
    volumes:
      - ./requirements/frontend/src:/usr/share/nginx/html
    ports:
      - "8001:8001"
    restart: on-failure

# Game container
  ludo:
    build:
      context: ./requirements/ludo
      dockerfile: Dockerfile
    volumes:
      - ./requirements/ludo/ludo_project:/app
    ports:
      - "8002:8002"
    networks:
      - atlas

# Profil container
  alfred:
    build:
      context: ./requirements/alfred
      dockerfile: Dockerfile
    volumes:
      - ./requirements/alfred/alfred_project:/app
    ports:
      - "8003:8003"
    networks:
      - atlas

# Tournament container
  coubertin:
    build:
      context: ./requirements/coubertin
      dockerfile: Dockerfile
    volumes:
      - ./requirements/coubertin/coubertin_project:/app
    ports:
      - "8004:8004"
    networks:
      - atlas

# Matchmaking container
  cupidon:
    build:
      context: ./requirements/cupidon
      dockerfile: Dockerfile
    volumes:
      - ./requirements/cupidon/cupidon_project:/app
    ports:
      - "8005:8005"
    networks:
      - atlas

# Authentification container
  petrus:
    build:
      context: ./requirements/petrus
      dockerfile: Dockerfile
    volumes:
      - ./requirements/petrus/petrus_project:/app
    ports:
      - "8006:8006"
    networks:
      - atlas

# Stats container
  mnemosine:
    build:
      context: ./requirements/mnemosine
      dockerfile: Dockerfile
    volumes:
      - ./requirements/mnemosine/mnemosine_project:/app
    ports:
      - "8007:8007"
    networks:
      - atlas

# Auth inter-container container
  lovelace:
    build:
      context: ./requirements/lovelace
      dockerfile: Dockerfile
    volumes:
      - ./requirements/lovelace/lovelace_project:/app
    ports:
      - "8008:8008"
    networks:
      - atlas

networks:
  atlas:
    driver: bridge
