# Generated by Django 5.0.1 on 2024-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pseudo',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='client',
            name='secondName',
            field=models.CharField(default='default', max_length=16),
            preserve_default=False,
        ),
    ]
