# Generated by Django 5.0.1 on 2024-01-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_pseudo_client_firstname_client_secondname'),
    ]

    operations = [
        migrations.CreateModel(
            name='myClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='client',
        ),
    ]
