# Generated by Django 5.0.1 on 2024-01-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_myclass_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('unique_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
                ('pseudo', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='', verbose_name='avatars/')),
            ],
        ),
        migrations.DeleteModel(
            name='myClass',
        ),
    ]
