# Generated by Django 5.0.1 on 2024-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_user_delete_myclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
