name: Build Check

on:
  pull_request:
    branches:
      - dev

jobs:
  build-check:
    name: Check Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
        
    - name: Build Project
      run: |
        make build