name: Build Check

on:
  pull_request:
    branches:
      - dev

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Start Docker Services
        run: |
            make build
            make up

      - name: Run Tests
        run: |
          if curl -ksSf https://localhost:8000/davinci/ >/dev/null; then
            echo "Grafana is up and running."
          else
            echo "Grafana is not running."
            exit 1
          fi
          if curl -ksSf https://localhost:8000/mensura/ >/dev/null; then
            echo "Prometheus is up and running."
          else
            echo "Prometheus is not running."
            exit 1
          fi

      - name: Stop Docker Services
        run: make down