name: Build Docker Containers

on:
  pull_request:
    branches:
      - dev  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build containers
      run: make debug