name: Build Docker Containers

on:
  push:
    branches:
      - TRA-237-Compile-ModSecurity-Quick-CI-Job-Health-Test
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build containers
      run: make all

    - name: Health Check
      run: curl -k https://localhost:8000/mensura/
