name: Build Check

on:
  pull_request:
    branches:
      - dev

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Start Docker Services
        run: |
            make build
            make up
            docker exec -it aegis curl -k https://aegis:8000/

      - name: Stop Docker Services
        run: make down